development:
  adapter: postgresql
  encoding: utf8
  database: ariip
  username: pedrolopes
  password: hcmt45
  host: 127.0.0.1
  port: 5432
  pool: 500
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: ariip
  username: postgres
  password: telematica
  host: 127.0.0.1
  port: 5432
  pool: 500
  timeout: 200
  wait_timeout: 300
  reconnect: true
  sslmode: disable
